version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "python database.py & python app.py"

volumes:
  db-data: